plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.runiverse'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

configurations {
	mockitoAgent
}

dependencies {
    // 환경변수 설정
	developmentOnly platform("me.paulschwarz:spring-dotenv-bom:5.0.1")
	developmentOnly "me.paulschwarz:springboot4-dotenv"

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.bouncycastle:bcprov-jdk18on:1.84'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
	//testImplementation 'org.springframework.boot:spring-boot-starter-security-test'

	// 기능
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation "com.github.f4b6a3:uuid-creator:6.1.1"

	implementation 'org.springframework.boot:spring-boot-starter-webmvc'

	// 프로토콜
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-redis-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-websocket-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	mockitoAgent('org.mockito:mockito-core') {
		transitive = false
	}
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()

	jvmArgs "-javaagent:${configurations.mockitoAgent.asPath}"
}

tasks.named('jar') {
	enabled = false
}