name: Backend CI/CD

on:
  push:
    branches:
      - dev

# workflows가 git repo에 접근할 수 있는 권한 설정
permissions:
  contents: read

# 같은 dev 브런치는 업데이트가 되면 가장 최신것만 실행됨
concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  # junit을 이용해서 단위테스트를 진행 (mock데이터 임으로 문제없이 진행해야 한다.)
  runiverse-backend-test:
    name: running-service 테스트 진행
    runs-on: ubuntu-24.04

    # 기본 파일 위치
    defaults:
      run:
        working-directory: running-service

    steps:
      # repo에 있는 정보를 사용할 수 있게 해준다.
      - name: Checkout backend
        uses: actions/checkout@v6

      # java 21 설치
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
          cache-dependency-path: |
            running-service/*.gradle*
            running-service/gradle/wrapper/gradle-wrapper.properties

      # gradlew 권한 부여
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # 단위 테스트 진행
      - name: Run unit tests
        run: ./gradlew test --no-daemon

  # docker build
  runiverse-backend-docker-build:
    name: running-service 도커 이미지 빌드
    needs: runiverse-backend-test
    runs-on: ubuntu-24.04

    permissions:
      contents: read # 이 git레포를 읽을 수 있는 권한을 준다.
      id-token: write # GitHub OIDC ID Token을 발급받을 수 있도록 허용한다.

    defaults:
      run:
        working-directory: running-service

    steps:
      # repo에 있는 정보를 사용할 수 있게 해준다
      - name: Checkout backend
        uses: actions/checkout@v6

      # java 21 설치
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
          cache-dependency-path: |
            running-service/*.gradle*
            running-service/gradle/wrapper/gradle-wrapper.properties

      # gradlew 권한 부여
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # 실행 가능한 jar 생성
      - name: Build bootJar
        run: ./gradlew bootJar -x test --no-daemon

      # buildIdx 세팅 (레이어 캐시 사용을 위해 필요)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # github OIDC 토큰
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ECR_PUSH_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: runiverse-ecr-push

      # ECR 로그인
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build 하고 push
      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v6
        with:
          context: running-service
          file: running-service/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_BACKEND_TEST_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_BACKEND_TEST_REPOSITORY }}:sha-${{ github.sha }}
          cache-from: type=gha,scope=runiverse-backend-test
          cache-to: type=gha,scope=runiverse-backend-test,mode=max